name: Build and deploy ASP.Net Core app to Azure Web App - app-lifeshare-davinci

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read   # Permissão necessária para fazer checkout de código

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true 

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{env.DOTNET_ROOT}}/myapp"

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: "398c6df6-93c7-4425-ade6-c30a2af90d10"
          tenant-id: "11dbbfe2-89b8-4549-be10-cec364e59551"
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C9E7B91BDCA7482C8199C68231A1BEAD }}
          allow-no-subscriptions: true

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-lifeshare-davinci'
          slot-name: 'Production'
          package: .
